package in.tutorlink.controller; import in.tutorlink.entity.*; import in.tutorlink.repository.*; import in.tutorlink.service.*; import org.springframework.web.bind.annotation.*; import org.springframework.security.core.annotation.*; import java.util.*;
@RestController public class WorkflowController { final ApplicationRepository apps;final TuitionRepository tuition;final UserRepository users;final NotificationRepository notes;final NotificationService notify;final MatchingService matching; final ActiveTuitionRepository active; final ReviewRepository reviews; final TutorProfileRepository profiles; public WorkflowController(ApplicationRepository a,TuitionRepository t,UserRepository u,NotificationRepository n,NotificationService no,MatchingService m,ActiveTuitionRepository at,ReviewRepository r,TutorProfileRepository p){apps=a;tuition=t;users=u;notes=n;notify=no;matching=m;active=at;reviews=r;profiles=p;}
 @PostMapping("/api/applications") Application apply(@AuthenticationPrincipal Long id,@RequestBody Map<String,Object> b){Long req=Long.valueOf(b.get("requirementId").toString());var r=tuition.findById(req).orElseThrow(()->new NoSuchElementException("Requirement not found"));var tutor=users.findById(id).orElseThrow();if(tutor.role!=Role.STUDENT)throw new IllegalArgumentException("Only students can apply");if(apps.existsByTutorIdAndRequirementId(id,req))throw new IllegalArgumentException("You already applied to this tuition");Application a=new Application();a.tutor=tutor;a.requirement=r;a.message=(String)b.getOrDefault("message","");apps.save(a);notify.send(r.parent,"New tutor application",tutor.fullName+" applied to your "+r.studentClass+" class requirement.");return a;}
 @GetMapping("/api/applications/my") List<Application> mine(@AuthenticationPrincipal Long id){var u=users.findById(id).orElseThrow();return u.role==Role.STUDENT?apps.findByTutorId(id):apps.findByRequirementParentId(id);}
 @PutMapping("/api/applications/{id}/status") Application status(@AuthenticationPrincipal Long uid,@PathVariable Long id,@RequestBody Map<String,String>b){Application a=apps.findById(id).orElseThrow();if(!a.requirement.parent.id.equals(uid))throw new IllegalArgumentException("Not authorized");ApplicationStatus next=ApplicationStatus.valueOf(b.get("status").trim().toUpperCase());if(next==ApplicationStatus.ACCEPTED&&!active.existsByApplicationId(id)){ActiveTuition at=new ActiveTuition();at.application=a;at.parent=a.requirement.parent;at.tutor=a.tutor;active.save(at);notify.send(a.tutor,"Tuition accepted","You have a new active tuition for "+a.requirement.studentClass+" class.");}a.status=next;apps.save(a);notify.send(a.tutor,"Application "+a.status.name().toLowerCase(),"Your application for "+a.requirement.studentClass+" class was "+a.status.name().toLowerCase()+".");return a;}
 @GetMapping("/api/matching/tutors/{id}") List<MatchingService.Match> matches(@PathVariable Long id){return matching.tutorsFor(tuition.findById(id).orElseThrow());}
 @GetMapping("/api/matching/jobs") List<TuitionRequirement> jobs(@AuthenticationPrincipal Long id){return tuition.findByActiveTrueOrderByCreatedAtDesc();}
 @GetMapping("/api/notifications") List<Notification> notifications(@AuthenticationPrincipal Long id){return notes.findByUserIdOrderByCreatedAtDesc(id);}
 @PutMapping("/api/notifications/{id}/read") Notification read(@AuthenticationPrincipal Long uid,@PathVariable Long id){var n=notes.findById(id).orElseThrow();if(!n.user.id.equals(uid))throw new IllegalArgumentException("Not authorized");n.read=true;return notes.save(n);}
 @GetMapping("/api/active-tuitions") List<ActiveTuition> active(@AuthenticationPrincipal Long id){var u=users.findById(id).orElseThrow();return u.role==Role.PARENT?active.findByParentId(id):active.findByTutorId(id);}
 @PutMapping("/api/active-tuitions/{id}/complete") ActiveTuition complete(@AuthenticationPrincipal Long uid,@PathVariable Long id){var at=active.findById(id).orElseThrow();if(!at.parent.id.equals(uid))throw new IllegalArgumentException("Only the parent can complete a tuition");at.status="COMPLETED";at.completedAt=java.time.Instant.now();at.application.status=ApplicationStatus.COMPLETED;apps.save(at.application);notify.send(at.tutor,"Tuition completed","Your tuition with "+at.parent.fullName+" for "+at.application.requirement.studentClass+" class has been marked completed.");return active.save(at);}
 @PostMapping("/api/reviews") Review review(@AuthenticationPrincipal Long uid,@RequestBody Map<String,Object>b){Long id=Long.valueOf(b.get("activeTuitionId").toString());ActiveTuition at=active.findById(id).orElseThrow();if(!at.parent.id.equals(uid)||!"COMPLETED".equals(at.status))throw new IllegalArgumentException("Only the parent can review a completed tuition");if(reviews.existsByActiveTuitionId(id))throw new IllegalArgumentException("This tuition has already been reviewed");int score=Integer.parseInt(b.get("rating").toString());if(score<1||score>5)throw new IllegalArgumentException("Rating must be between 1 and 5");Review r=new Review();r.activeTuition=at;r.parent=at.parent;r.tutor=at.tutor;r.rating=score;r.text=(String)b.getOrDefault("text","");reviews.save(r);var all=reviews.findByTutorId(at.tutor.id);TutorProfile p=profiles.findByUserId(at.tutor.id).orElse(null);if(p!=null){p.rating=all.stream().mapToInt(x->x.rating).average().orElse(0);p.completedTuitions=(int)active.findByTutorId(at.tutor.id).stream().filter(x->"COMPLETED".equals(x.status)).count();profiles.save(p);}return r;}
 @GetMapping("/api/reviews/tutor/{id}") List<Review> tutorReviews(@PathVariable Long id){return reviews.findByTutorIdOrderByCreatedAtDesc(id);}}
